# https://vuepress.vuejs.org/zh/guide/deploy.html#github-pages
name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env: # 部署到本仓库的 gh-pages 分支
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: cxy35/website-vuepress
          TARGET_BRANCH: gh-pages
          BUILD_SCRIPT: yarn && yarn build
          BUILD_DIR: docs/.vuepress/dist
          COMMIT_MESSAGE: 'Auto deploy from Github Actions'
          # CNAME: https://vuepress.cxy35.com