# 部署方法2：https://github.com/jenkey2011/vuepress-deploy
# 每次推送代码，将自动构建、部署到 cxy35/website-vuepress 的 gh-pages 分支，注意在 Pages 的设置中需要指定到该分支
name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env: # 部署到本仓库的 gh-pages 分支
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: cxy35/website-vuepress
          TARGET_BRANCH: gh-pages
          # BUILD_SCRIPT: yarn && yarn build
          BUILD_SCRIPT: npm install && npm run docs:build
          BUILD_DIR: docs/.vuepress/dist
          COMMIT_MESSAGE: Auto deploy from Github Actions
          # CNAME: https://vuepress.cxy35.com